version: "3.3"

services:
  api:
    image: sendinair/exchange_server
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    ports:
      - 3030:3030
    depends_on:
      - nats
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  usdt.btc.exchange:
    image: sendinair/exchange_server
    env_file: docker-compose.env
    environment:      
      SERVICES: usdt.btc.exchange
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats:alpine3.14
    networks:
      - internal    

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
    ports:
      - 3000:80
      - 443:443
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:
  default:

volumes:
  data: