version: "3.3"

services:
  api:
    image: sendinair/nft-server
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: $PORT
    ports:
      - 3030:3030
    depends_on:
      - nats
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=$PORT"
    networks:
      - internal

  blockchain.ethereum:
    image: sendinair/nft-server
    env_file: docker-compose.env
    environment:      
      SERVICES: blockchain.ethereum
    depends_on:
      - nats
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blockchain.ethereum.nft:
    image: sendinair/nft-server
    env_file: docker-compose.env
    environment:      
      SERVICES: blockchain.ethereum.nft
    depends_on:
      - nats
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blockchain.klaytn:
    image: sendinair/nft-server
    env_file: docker-compose.env
    environment:      
      SERVICES: blockchain.klaytn
    depends_on:
      - nats
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  blockchain.klaytn.nft:
    image: sendinair/nft-server
    env_file: docker-compose.env
    environment:      
      SERVICES: blockchain.klaytn.nft
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats:alpine3.14
    environment:
      PORT: $PORT
    networks:
      - internal    

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
    ports:
      - $PORT:80
      - 443:443
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:
  default:

volumes:
  data: